kind: Deployment
apiVersion: apps/v1
metadata:
 name: nginx-dep
 namespace: nginx
spec:
 replicas: 2 
 selector:
  matchLabels:
   app: nginx
 template:
  metadata: 
   name: nginx-pod 
   labels:
    app: nginx
  spec:
   containers:
   - name: nginx-container
     image: nginx:latest
     ports: 
     - containerPort: 80 
     volumeMounts: 
     - mountPath: /var/www/html
       name: my-vol
   volumes:
   - name: my-vol
     persistentVolumeClaim:
      claimName: local-pvc
